// vue3-app/src/components/ToDoItem.vue
<script setup lang="ts">
import type { HandleToDosOption } from '@/compositions/todo';
import { computed, withDefaults } from 'vue';
import { HANDLE_TO_DO_TYPE } from '../../../core/constant';

interface ToDoItemProps {
  handleCheckbox: (options: HandleToDosOption) => void
  completed: boolean
  title: string
  id: number
}

const props = withDefaults(defineProps<ToDoItemProps>(), {
  handleCheckbox : () => {},
  completed: false,
  title: '',
  id: NaN
})

const itemTextClasses = computed(() => ({
  'item-text': true,
  'checked-item-text': props.completed
}))

</script>

<template>
  <li class="todo-item" @click="() => props.handleCheckbox({type: HANDLE_TO_DO_TYPE.CHECK, id: props.id})">
    <input type="checkbox" class="todo-input" :checked="props.completed"/>
    <p :class="itemTextClasses">{{title}}</p>
  </li>
</template>

<style scoped>
@import "../../../core/styles/toDoItem.css";

</style>

// react-app/src/app/_components/ToDoItem.tsx
import "../../../../core/styles/toDoList.css"

import { HANDLE_TO_DO_TYPE } from "../../../../core/constant"
import { HandleToDosOption } from "../_hooks/todo"

interface ToDoItemProps {
  handleCheckbox: (options: HandleToDosOption) => void
  completed: boolean
  title: string
  id: number
}

export default function ToDoItem(props: ToDoItemProps) {
  return (
    <li
      className="todo-item"
      onClick={() =>
        props.handleCheckbox({ type: HANDLE_TO_DO_TYPE.CHECK, id: props.id })
      }
    >
      <input type="checkbox" className="todo-input" defaultChecked={props.completed} />
      <p className="itemTextClasses">{props.title}</p>
    </li>
  )
}
