// react-app/src/app/page.tsx
"use client"

import Image from "next/image"
import logo from "../../public/logo.svg"
import "../../../core/styles/app.css"
import {
  TO_DO_PLACEHOLDER,
  MOCK_USER_ID,
  HANDLE_TO_DO_TYPE,
} from "../../../core/constant/index"
import { useEffect, useMemo, useRef, useState } from "react"
import { useToDo } from "./_hooks/todo"
import ToDoItem from "./_components/ToDoItem"

export default function ToDoApp() {
  const [title, setTitle] = useState("")
  const {
    fetchReadUserTodos,
    state: appState,
    handleToDos,
  } = useToDo(MOCK_USER_ID)

  const todoItemsRef = useRef<HTMLUListElement>(null)

  const totalCount = useMemo(() => appState.todos.length, [appState.todos])
  const checkedCount = useMemo(
    () => appState.todos.filter((todo) => todo.completed).length,
    [appState.todos]
  )

  useEffect(() => {
    fetchReadUserTodos()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const addCheckBox = () => {
    handleToDos({ type: HANDLE_TO_DO_TYPE.ADD, title })
    setTitle("")

    setTimeout(() => {
      if (todoItemsRef.current) {
        todoItemsRef.current.scrollTo({
          top:
            todoItemsRef.current.scrollHeight +
            todoItemsRef.current.clientHeight,
        })
      }
    }, 0)
  }

  return (
    <section className="container">
      <div className="todo-wrapper">
        <div className="todo-header">
          <Image
            alt="Next logo"
            className="logo"
            src={logo}
            width="80"
            height="125"
          />
          <h2>To-do list</h2>
        </div>
        <form
          className="input-form"
          onSubmit={(e) => {
            e.preventDefault()
            addCheckBox()
          }}
        >
          <input
            type="text"
            className="input-field"
            id="todoInput"
            placeholder={TO_DO_PLACEHOLDER}
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            disabled={appState.loading.fetchReadUserTodos}
          />
          <button
            className="input-btn"
            disabled={appState.loading.fetchReadUserTodos || !title.length}
          >
            추가
          </button>
        </form>
        {appState.loading.fetchReadUserTodos ? (
          <div className="todo-items">데이터를 불러오는 중입니다.</div>
        ) : (
          <ul className="todo-items" ref={todoItemsRef}>
            {appState.todos.map((todo) => (
              <div key={todo.id} className="todo-item-wrapper">
                <ToDoItem
                  id={todo.id}
                  title={todo.title}
                  completed={todo.completed}
                  handleCheckbox={handleToDos}
                />
              </div>
            ))}
          </ul>
        )}

        <div>
          <div className="counter-container">
            <p>
              <span>{checkedCount}</span>
              <span> / </span>
              <span>{totalCount}</span>
            </p>
            <button
              onClick={() => handleToDos({ type: HANDLE_TO_DO_TYPE.INIT })}
              disabled={appState.loading.fetchReadUserTodos}
            >
              Delete All
            </button>
          </div>
        </div>
      </div>
    </section>
  )
}

// vue3-app/src/App.vue
<script setup lang="ts">
  import { computed, ref } from 'vue';
  import { TO_DO_PLACEHOLDER, MOCK_USER_ID, HANDLE_TO_DO_TYPE } from '../../core/constant/index'
  import ToDoItem from './components/ToDoItem.vue';
  import { useToDo } from './compositions/todo';

  const title = ref('')
  const {fetchReadUserTodos, state: appState, handleToDos } = useToDo(MOCK_USER_ID)

  const todoItemsRef = ref<HTMLUListElement | null>(null)

  fetchReadUserTodos()

  const totalCount = computed(() => appState.todos.length)
  const checkedCount = computed(() => appState.todos.filter(todo => todo.completed).length)

  const addCheckBox = () => {
    handleToDos({type: HANDLE_TO_DO_TYPE.ADD, title: title.value})
    title.value = ''

    setTimeout(()=> todoItemsRef.value?.scrollTo({
      top: todoItemsRef.value?.scrollHeight + todoItemsRef.value?.clientHeight 
    }), 0)
  }
</script>

<template>
  <section class="container">
    <div class="todo-wrapper">
      <div class="todo-header">
        <img alt="Vue logo" class="logo" src="@/assets/logo.svg" width="125" height="125" />
        <h2>To-do list</h2>
      </div>
      <form 
        class="input-form"
        @submit.prevent="addCheckBox"
      >
        <input
          type="text"
          class="input-field"
          id="todoInput"
          :placeholder="TO_DO_PLACEHOLDER"
          v-model="title"
          :disabled="appState.loading.fetchReadUserTodos"
        />
        <button 
          class="input-btn"
          :disabled="appState.loading.fetchReadUserTodos || !title.length"
        >
          추가
        </button>
      </form>
      <div v-if="appState.loading.fetchReadUserTodos" class="todo-items">
        데이터를 불러오는 중입니다.
      </div>
      <ul v-else class="todo-items" ref="todoItemsRef">
        <div 
          v-for="todo in appState.todos" 
          :key="todo.id" 
          class="todo-item-wrapper"
        >
          <ToDoItem 
            :id="todo.id"
            :title="todo.title" 
            :completed="todo.completed"
            :handle-checkbox="handleToDos"
          />
        </div>
      </ul>
      <div>
        <hr class="counter" />
        <div class="counter-container">
          <p>
            <span>{{ checkedCount }}</span>
            <span> / </span>
            <span>{{ totalCount }}</span>
          </p>
          <button 
            @click="() => handleToDos({type: HANDLE_TO_DO_TYPE.INIT})"
            :disabled="appState.loading.fetchReadUserTodos"
          >
            Delete All
          </button>
        </div>
      </div>
    </div>
  </section>
</template>

<style scoped>
  @import '../../core/styles/app.css';

</style>
